### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mebjas** [mebjas/Wiki-Read-Mode#1]
**Features requires in version 1.0.0 release**
- [x] The popup should be functional
- [x] Better UI for popup
- [x] Better UI for the inpage menu
- [x] Automatic show hide on document scroll
- [x] Search capability to inpage menu
